---
title: "Instacart Data Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r data setup, include=FALSE}
data("instacart")

instacart = 
  instacart |> 
  as_tibble()

instacart_aisles = 
  instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  filter(n < 10000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Scatterplot

```{r scatterplot}
instacart_aisles |> 
  mutate(text_label = str_c("Aisle: ", aisle, "\nNumber: ", n)) |> 
  plot_ly(
    x = ~aisle, y = ~n, type = "scatter", mode = "markers",
    color = ~aisle, alpha = 0.75, size = 0.5, colors = "viridis", text = ~text_label) |> 
  layout(title = "Aisles ordered from in Instacart")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Barplot

```{r barplot}
instacart_aisles |> 
  mutate(aisle = fct_reorder(aisle, n))|> 
  plot_ly(
    x = ~aisle, y = ~n, type = "bar", mode = "markers",
    color = ~aisle, colors = "viridis") |> 
  layout(title = "Aisles ordered from in Instacart")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C: 

```{r }
instacart_aisles |> 
  filter(aisle %in% c("packaged meat", "packaged poultry", "packaged seafood")) |> 
  plot_ly(y = ~n, color = ~aisle, type = "histogram") |> 
  layout(title = "Distribution of Number of Items ordered from Selected Aisles")
```




