---
title: "Plotly Dashboard"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Problem 2

## Loading data

We're going to look into the `NOAA` dataset. 

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31")

weather_df = 
  weather_df|>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Plotly Plots

### Scatterplot

```{r}
weather_df |> 
  mutate(text_label = str_c("Name: ", name, "\nPrcp: ", prcp, "\nDate: ", date)) |> 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~name, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5, colors = "viridis")
```


### Boxplot

```{r}
weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> 
  plot_ly(y = ~tmax, color = ~name, type = "box", colors = "viridis")
```


### Barplot?












